# Keep alphabetical and formatted correctly please
[versions]
gradle-ktlint                   = "13.1.0"
h2                              = "2.4.240"
kotest                          = "6.0.5"
kotlin                          = "2.2.21"
spring                          = "4.0.0"

[libraries]
# Main
kotlin-stdlib                   = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
spring-boot-starter-data-jpa    = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring" }

# Test
h2                              = { module = "com.h2database:h2", version.ref = "h2" }
kotest-assertions-core          = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-table         = { module = "io.kotest:kotest-assertions-table", version.ref = "kotest" }
kotest-extensions-spring        = { module = "io.kotest:kotest-extensions-spring", version.ref = "kotest" }
kotest-runner-junit5            = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
spring-boot-starter-test        = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring" }


[bundles]
kotest                          = [
                                    "kotest-assertions-core" ,
                                    "kotest-assertions-table",
                                    "kotest-extensions-spring",
                                    "kotest-runner-junit5"
                                  ]
spring-test                     = [
                                    "spring-boot-starter-data-jpa",
                                    "spring-boot-starter-test"
                                  ]

[plugins]
gradle-ktlint                   = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "gradle-ktlint" }
kotlin-jpa                      = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlin-spring                   = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jvm                      = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
